name: "🚀 publish"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: 🚀 publish
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2.1.1
      - name: 🟢 node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
        env:
          envFile: .env
      - name: 📦 install dependencies
        run: npm install
      - name: 📝 build
        run: npm run build
      - name: 🚀 publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
